name: Compile NSS Packages

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/qosmio/nss-packages.git
  REPO_BRANCH: NSS-12.4-K6.x
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setting up build environment
      run: |
        mkdir -p $GITHUB_WORKSPACE/build
        sudo chown -R $USER:$GROUPS $GITHUB_WORKSPACE/build

    - name: Clone source code
      run: |
        git clone ${{ env.REPO_URL }} $GITHUB_WORKSPACE/nss-packages --branch ${{ env.REPO_BRANCH }} --single-branch

    - name: Prepare build environment for OpenWrt packages
      run: |
        sudo apt update && sudo apt install -y build-essential libncurses5-dev libncursesw5-dev \
        zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python

    - name: Sync the source code (if necessary)
      run: |
        cd $GITHUB_WORKSPACE/nss-packages
        git pull

    - name: Compile .ipk package
      run: |
        cd $GITHUB_WORKSPACE/nss-packages
        # Make sure the following compile command is compatible with your Makefile or build script
        make package/compile V=s

    - name: Find .ipk files
      run: |
        ipk_files=$(find $GITHUB_WORKSPACE/nss-packages/bin/packages -type f -name "*.ipk")
        if [ -z "$ipk_files" ]; then
          echo "No .ipk files found."
          exit 1
        fi
        mv $ipk_files $GITHUB_WORKSPACE/build/

    - name: Upload compiled .ipk packages
      uses: actions/upload-artifact@v2
      with:
        name: nss-packages-ipks
        path: $GITHUB_WORKSPACE/build/*.ipk

    - name: Create Release and upload .ipk packages
      if: env.UPLOAD_RELEASE == 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: $GITHUB_WORKSPACE/build/*.ipk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
