name: Compile NSS Packages

on: workflow_dispatch

env:
  REPO_URL: https://github.com/qosmio/nss-packages
  REPO_BRANCH: main
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  compile-nss-packages:
    runs-on: ubuntu-latest
    steps:
    - name: Set up working environment
      run: |
        mkdir -p $GITHUB_WORKSPACE/build
        sudo chown $USER:$GROUPS $GITHUB_WORKSPACE/build
        
    - name: Checkout NSS packages code
      uses: actions/checkout@v3
      with:
        repository: qosmio/nss-packages
        path: 'nss-packages'
        ref: ${{ env.REPO_BRANCH }}
      
    - name: Prepare build environment for OpenWrt packages
      run: |
        sudo apt update && sudo apt install -y build-essential libncurses5-dev libncursesw5-dev \
        zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python
      
    - name: Compile .ipk package
      run: |
        cd nss-packages
        # Assuming the Makefile is located in the root of `nss-packages` repository
        # If the Makefile is elsewhere within the repository, change the working directory accordingly
        make package/compile V=s
      
    - name: Find the .ipk files
      run: |
        # This finds any .ipk files that were created during the build and moves them to the upload directory
        ipk_files=$(find $GITHUB_WORKSPACE -name '*.ipk' -type f)
        echo "Found .ipk files: $ipk_files"
        mkdir -p $GITHUB_WORKSPACE/build
        mv $ipk_files $GITHUB_WORKSPACE/build

    - name: Upload compiled .ipk packages
      uses: actions/upload-artifact@v2
      with:
        name: nss-packages-ipks
        path: $GITHUB_WORKSPACE/build/*.ipk

    - name: Create Release and upload .ipk packages
      if: env.UPLOAD_RELEASE == 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: $GITHUB_WORKSPACE/build/*.ipk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
